### ISSUE TITLE
データの誤字

### ISSUE THREAD

**Issue by Himeyama** [nishidayoshikatsu/covid19-yamaguchi-opendata#46]
https://nishidayoshikatsu.github.io/covid19-yamaguchi-opendata/patients.json の1903例目の居住地に誤字があるようなのですが…

![image](https://user-images.githubusercontent.com/39254183/117900194-acc81680-b303-11eb-8821-2b412424ba0e.png)

**Comment by nisshi-dev** [comment]
@Himeyama 
ありがとうございます。
一部の誤字脱字に対して、対応できるように修正を行います。

また、山口県のオープンデータ更新をされている方にもお伝えいたします。
