### ISSUE TITLE
年末年始に日付の誤り

### ISSUE THREAD

**Issue by Himeyama** [nishidayoshikatsu/covid19-yamaguchi-opendata#52]
年末年始の多く (37件、No. 5854-5890) に日付の誤りが見られます。

https://nishidayoshikatsu.github.io/covid19-yamaguchi-opendata/patients.json

![image](https://user-images.githubusercontent.com/39254183/148641895-2b28a694-f0c7-4e17-9831-177a6333b7d1.png)

山口県のオープンデータにも同じ間違いが見られました。

**Comment by nisshi-dev** [comment]
@Himeyama 
ご指摘ありがとうございます！
確認次第、オープンデータ担当の方に連絡し修正の依頼を送信いたします。

**Comment by Himeyama** [comment]
オープンデータ側で修正が行われていることを確認しました。
現在 GitHub Actions による json ファイルの出力はうまくできていないようですが、この件については解決の目途が立ちそうなので閉じます。
ご連絡ありがとうございました。
